Allow for trivial changes
BFHS-Open/constitution pull request #5
Opened 2023-07-21 17:45 UTC by Aeshus

Currently it's quite onerous to require any and all changes to the constitution to require adding an amendment.

Simple stuff like formatting and build-system changes definitely should not need a description appended, and it will instead just clutter up the page.

I went with non-semantic changes as there's always some change that could be made of word choice, and as long as it doesn't change the meaning or interpretation of the document, it will be allowed.

2023-07-22 18:49 UTC, cuppajoe123 approved these changes
Looks good

2023-07-23 00:32 UTC, EmeraldBlock requested changes
nice, just one minor but semantic thing

2023-07-23 00:32 UTC, EmeraldBlock commented on articles/article-08.tex
> +		you must include a one-sentence description in \refarticle{Amendments}.
The phrasing "one-sentence description" prevents longer descriptions.

2023-07-24 09:07 UTC, EmeraldBlock approved these changes

2023-07-25 00:49 UTC, merged